Formula
obennet/sed-backend pull request #82
Opened 2023-04-04 07:00 UTC by obennet

works for value drivers and external factors

2023-04-04 07:10 UTC, obennet commented
Failing tests are the ones connected to running simulation with files. Same as others PR

2023-04-05 19:28 UTC, EppChops requested changes
The parser seems to always change the VD's and the EF's to 0, no matter what. See attached screen shots of formulas and sim results. Please fix parsing <3


It does run tho ;)

![Screenshot_2023-04-05_22-26-05](https://user-images.githubusercontent.com/57296415/230184568-12ae85ea-7627-4940-846a-694d8b15bad2.png)
![Screenshot_2023-04-05_22-26-14](https://user-images.githubusercontent.com/57296415/230184575-9e8170c4-7ff9-444f-8287-0f7bafc74a49.png)
![Screenshot_2023-04-05_22-27-12](https://user-images.githubusercontent.com/57296415/230184577-bad4e175-c8ed-4faa-bd17-1d0cd2dbaf65.png)

2023-04-05 19:28 UTC, EppChops commented on sedbackend/apps/cvs/simulation/storage.py
>  # TODO fix how the formulas are parsed
Shouldn't leave old code commented out

2023-04-05 19:28 UTC, EppChops commented on sedbackend/apps/cvs/simulation/storage.py
> +    new_formula = expr.remove_strings_replace_zero(new_formula)
I don't know if this line but something in the parsing does not work right.

Got the following error with the given input:
![Screenshot_2023-04-05_22-21-57](https://user-images.githubusercontent.com/57296415/230183714-bcd32a5a-afe7-4f1e-be25-c0779e873da7.png)
![Screenshot_2023-04-05_22-22-10](https://user-images.githubusercontent.com/57296415/230183722-5fb25e60-ac89-4b63-ba19-dc25648ca143.png)

2023-04-12 09:29 UTC, EppChops commented
Hi!

I hate to tell you but the parsing still doesn't work correctly. I have two examples, the first ones with no division by zero, and the last one with division by zero which gives error "Could not parse formula":

Example 1:
![Screenshot_2023-04-12_12-15-54](https://user-images.githubusercontent.com/57296415/231415227-7db29d53-a268-44d7-9f27-9eebdab4b345.png)
![Screenshot_2023-04-12_12-19-52](https://user-images.githubusercontent.com/57296415/231415237-cc707322-b822-4078-81a4-c87a7ef43785.png)
![Screenshot_2023-04-12_12-20-06](https://user-images.githubusercontent.com/57296415/231415240-1ef15ae8-1613-453a-bc49-619e25ae7122.png)
![Screenshot_2023-04-12_12-21-25](https://user-images.githubusercontent.com/57296415/231415329-00800a48-f872-4d1e-95ed-68ae7d12c26a.png)

Example 2:
![Screenshot_2023-04-12_12-22-52](https://user-images.githubusercontent.com/57296415/231415451-df2fcf45-a751-4da6-821f-765267f8a2de.png)
![Screenshot_2023-04-12_12-23-06](https://user-images.githubusercontent.com/57296415/231415452-023df78b-2689-41e5-8ff1-d4f68741eff0.png)
![Screenshot_2023-04-12_12-23-15](https://user-images.githubusercontent.com/57296415/231415455-b73b76f5-0281-4a3d-adea-0100c73071b4.png)

Final example with divison by zero (rather, no values in the VD's);
![Screenshot_2023-04-12_12-28-59](https://user-images.githubusercontent.com/57296415/231416180-19eaac40-08d9-470c-a74d-512fc4f6e29d.png)

2023-04-12 10:03 UTC, EppChops commented
Found another thing. 

With the following formulas: 
![Screenshot_2023-04-12_13-02-02](https://user-images.githubusercontent.com/57296415/231425048-ce43f236-aa05-49dc-95e8-382d52795c91.png)


The simulation does work when no values on VD's are set, as can be seen here: 
![Screenshot_2023-04-12_13-00-28](https://user-images.githubusercontent.com/57296415/231425175-074d0865-57f5-4f8d-bcbf-2200d0f3131d.png)
![Screenshot_2023-04-12_13-00-51](https://user-images.githubusercontent.com/57296415/231425179-0a83a41a-d6b1-400d-9a48-d0bef9427545.png)


But it does not work when I put values to my VD's:
![Screenshot_2023-04-12_13-01-18](https://user-images.githubusercontent.com/57296415/231425269-91314b3d-b782-4178-bd53-9721a148e323.png)
![Screenshot_2023-04-12_13-01-32](https://user-images.githubusercontent.com/57296415/231425271-32d7d17e-b853-4379-b91a-55f9c5898fbc.png)

2023-04-13 09:11 UTC, EppChops commented
LGTM good job!

2023-04-13 09:11 UTC, merged